version: 2.1
orbs:
  win: circleci/windows@2.2.0
  browser-tools: circleci/browser-tools@0.1.3
jobs:
  'node-10':
    docker:
      - image: circleci/node:10.17.0-browsers
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run test

  'node-12':
    docker:
      - image: circleci/node:12.13.1-browsers
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run test

  windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run: choco install googlechrome
      - run: yarn install --frozen-lockfile
      - run: yarn run test

  mac:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: yarn install --frozen-lockfile
      - run: yarn run test

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-12'
      - 'windows'
      - 'mac'
