version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10.17.0-browsers
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run test
  'node-12':
    docker:
        - image: circleci/node:12.13.1-browsers
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run test

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-12'
